# Generated by Django 2.2.12 on 2022-05-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.user')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
    ]
