# Generated by Django 3.1.7 on 2022-05-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recommendations',
        ),
    ]
